module:
  imports:
    - path: github.com/google/docsy
      ignoreConfig: true
    - path: github.com/google/docsy/dependencies
  replacements:
    - path: github.com/google/docsy/dependencies
      dir: .
