# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
  command = "npm ci && npm run build:production"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.2"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"
  GO_VERSION = "1.20"

[context.production]
command = "npm run build:production"

# Redirect all 404s to our custom 404 page
[[redirects]]
  from = "/*"
  to = "/he/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
